 context.modules = [
 {   name = libpipewire-module-protocol-simple
     args = {
         # Provide sink
         capture = true
         audio.rate = 48000
         audio.format = S16
         audio.channels = 2
         audio.position = [ FL FR ]
 
         # The addresses this server listens on for new
         # client connections
         server.address = [
             "tcp:127.0.0.1:4711"
         ]
         capture.props = {
             # Make this a sink instead of a capture stream
             media.class = Audio/Sink
             node.name = "snapcast_sink"
             node.description = "Snapcast Sink"
         }
     }
 }
 ]
 
